const stars = [
    {
        id: 1,
        name: "Sirio",
        price: 300,
        size: "Enana blanca",
        description: "La estrella, ubicada en la constelación Can Mayor, se encuentra a 8,6 años luz de distancia.",
        image: 'Assets/Pictures/Sirio.jpg',
        seller: "Amazon",
    },
    {
        id: 2,
        name: "Canopus",
        price: 500,
        size: "Supergigante blanco-amarilla",
        description: "Una estrella sin igual, ubicada en la constelación Carina, que se encuentra a 309,8 años luz de distancia.",
        image: '',
        seller: "NASA",
    },
    {
        id: 3,
        name: "Arturo",
        price: 350,
        size: "Gigante naranja",
        description: "La estrella Arturo, ubicada en la constelación Boyero, se encuentra a 36,7 años luz de distancia.",
        image: '',
        seller: "NASA",
    },
    {
        id: 4,
        name: "Alfa Centauri A",
        price: 50,
        size: "Enana amarilla",
        description: "Una pequeña estrella, muy llamativa, ubicada en la constelación Centauro, que se encuentra a 4,37 años luz de distancia.",
        image: '',
        seller: "NASA",
    },
    {
        id: 5,
        name: "Hadar",
        price: 100,
        size: "Gigante blanca",
        description: "La estrella Hadar, ubicada en la constelación Centauro, se encuentra a 530 años luz de distancia.",
        image: '',
        seller: "Ebay",
    },
    {
        id: 6,
        name: "Altair",
        price: 50,
        size: "Enana blanca",
        description: "Una pequeña estrella, muy llamativa, ubicada en la constelación Águila, que se encuentra a 16,8 años luz de distancia.",
        image: '',
        seller: "Tesla Space",
    },
    {
        id: 7,
        name: "Betelgeuse",
        price: 600,
        size: "Supergigante roja",
        description: "La estrella Betelgeuse, ubicada en la constelación Orión, se encuentra a 640 años luz de distancia.",
        image: '',
        seller: "NASA",
    },
    {
        id: 8,
        name: "Fomalhaut",
        price: 800,
        size: "Enana-subgigante blanca",
        description: "Una pequeña estrella, muy llamativa, ubicada en la constelación Piscis Austrinus, que se encuentra a 25 años luz de distancia.",
        image: '',
        seller: "Caixa Bank",
    },
]